### ISSUE TITLE
Results explanation

### ISSUE THREAD

**Issue by mfe7** [kibeomKim/House3D_baseline#1]
Hi,

Thank you for sharing this implementation of a House3D baseline!

A couple questions
1) How long did training take and on what type of computer?
2) Regarding your results plot, do you mean that you trained/tested on only 5 of the same houses?
3) What is considered a failure? The agent doesn't reach the goal within some pre-defined time? Or gets stuck and would never reach the goal given infinite time?

**Comment by kibeomKim** [comment]
Hi, thanks for your attention.

1. How long did training take and on what type of computer?
My machine have 2 Intel Xeon E5-2630 v4 (10 cores, 2.2GHz) and 4 Titan Xp. It took about 3 days to learn.

2. Regarding your results plot, do you mean that you trained/tested on only 5 of the same houses?
In the implementation, It learned 20 houses and training 5 house that same with training, because the baseline in the paper used 120 or 200 cpu cores only for training.

3. What is considered a failure? The agent doesn't reach the goal within some pre-defined time? Or gets stuck and would never reach the goal given infinite time?

It has to be in the target room within 100 steps.

In the paper, 
An episode is considered successful if both of the following two criteria are satisfied: (1) the agent is located inside the target room; (2) the agent consecutively sees a designated object category associated with that target room type for at least 2 time steps. We assume that an agent sees an object if there are at least 4% of pixels in current observation belonging to that object.

**Comment by mfe7** [comment]
Thank you for the quick response! Questions 1 and 3 are clear to me now. Still unclear on #2: How many houses did you train on? How many houses did you test on? Were the test houses the same or different from the training houses?

**Comment by kibeomKim** [comment]
I used 20 houses for training and selected 5 houses for the test in the training house.
so the same with the training set.
